main:
  - name: Home
    url: "/"
    weight: 10

  - name: Publications
    url: "/publications/"
    weight: 20

  - name: Commentary & Media
    url: "/media/"
    weight: 30


  - name: Code
    url: "/code/"
    weight: 50
